version: '3.8'

services:
  elasticmq:
    image: softwaremill/elasticmq
    container_name: elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    command: -Dconfig.file=/opt/elasticmq.conf
